name: GKE dev

on:
  push:
    tags:
      - "r[0-9]*"

env:
  GCE_PROJECT: wallet-prod-314018
  GAR_LOCATION: europe-west3
  GAR_REPO: jupiter-quote-api-repo
  REGISTRY: europe-west3-docker.pkg.dev
  DOCKER_BUILDKIT: 1

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.CI_DEPLOY_KEY }}

      # Build the Docker image
      - name: Build jupiter quote api
        run: |-
          docker build --ssh default --platform linux/amd64 --tag "$REGISTRY/$GCE_PROJECT/$GAR_REPO/jupiter-quote-api:$GITHUB_REF_NAME" --file devops/docker/Dockerfile .
      - id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GAR_CREDENTIALS }}
          token_format: access_token

      - uses: 'docker/login-action@v1'
        with:
          registry: ${{ env.REGISTRY }}
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      # Publish the Docker image
      - name: Publish jupiter quote API
        run: |-
          docker push "$REGISTRY/$GCE_PROJECT/$GAR_REPO/jupiter-quote-api:$GITHUB_REF_NAME"
      # Clone, Parse and Update Helm Values
      - name: Install yq
        uses: mikefarah/yq@v4.27.3

      - name: Clone Helm Chart Repository
        uses: actions/checkout@v3
        with:
          repository: p2p-org/p2p-wallet-helm-charts
          path: helm-chart
          ref: main
          token: ${{ secrets.CI_DEPLOY_TOKEN }}

      - name: Update Helm Values
        run: |
          cd helm-chart
          yq e -i '.image.tag |= strenv(GITHUB_REF_NAME)' charts/jupiter-quote-api/values.dev.yaml
          git config --global user.email "github@p2p.org"
          git config --global user.name "Github Actions"
          git add charts/jupiter-quote-api/values.dev.yaml
          git commit -m "Release $GITHUB_REF_NAME"
          git push
